

$(function(){var last_scroll=0;var last_scroll_banner=0;last_scroll=checkScroll(last_scroll,$(window).scrollTop());last_scroll_banner=checkScrollBanner(last_scroll_banner,$(window).scrollTop());window.addEventListener('scroll',(e)=>{last_scroll=checkScroll(last_scroll,$(window).scrollTop());last_scroll_banner=checkScrollBanner(last_scroll,$(window).scrollTop());});});function checkScroll(last_scroll,scroll){if(scroll>30){$('.navbar').addClass('with-bg');}else{$('.navbar').removeClass('with-bg');}
if(scroll>=last_scroll){$('.navbar').addClass('navbar-hide');}else{$('.navbar').removeClass('navbar-hide');}
if(scroll<=50){$('.navbar').removeClass('navbar-hide');}
let vector=200-scroll/10;$('#left-ships').css({transition:'all 0.1s ease','-webkit-transform':'translate3d('+vector+'px,'+vector+'px,0)'});$('#right-ships').css({transition:'all 0.1s ease','-webkit-transform':'translate3d('+vector*-1+'px,'+vector+'px,0)'});return scroll;}
function checkScrollBanner(last_scroll,scroll){if(scroll>=last_scroll){$('#top-bar').addClass('top-bar-hide');$('.navbar').addClass('top-0');}else{$('#top-bar').removeClass('top-bar-hide');$('.navbar').removeClass('top-0');}
if(scroll<=50){$('#top-bar').removeClass('top-bar-hide');$('.navbar').removeClass('top-0');}
let vector=200-scroll/10;return scroll;}
function closeModal(modalId){$(modalId).modal('hide');}
var swiper1=new Swiper('.blockchain-swiper',{slidesPerView:1.2,spaceBetween:12,navigation:{nextEl:'.swiper-next',prevEl:'.swiper-prev',},breakpoints:{0:{slidesPerView:1.2,spaceBetween:12,},576:{slidesPerView:1.2,spaceBetween:12,},768:{slidesPerView:2.4,spaceBetween:12,},992:{slidesPerView:3,spaceBetween:24,},1200:{slidesPerView:3,spaceBetween:24,},},});var swiper2=new Swiper('.metaverse-swiper',{initialSlide:1,centeredSlides:true,slidesPerView:1,spaceBetween:24,autoHeight:true,updateOnWindowResize:true,navigation:{nextEl:'.swiper-metaverse-next',prevEl:'.swiper-metaverse-prev',},pagination:{el:".metaverse-swiper-pagination",},breakpoints:{0:{slidesPerView:1,spaceBetween:24,initialSlide:0,},576:{slidesPerView:1,spaceBetween:24,initialSlide:0,},768:{slidesPerView:2.05,spaceBetween:24,},992:{slidesPerView:3,spaceBetween:24,},1200:{slidesPerView:3,spaceBetween:24,},},});var swiper3=new Swiper('.charity-swiper',{slidesPerView:1,spaceBetween:10,navigation:{nextEl:'.swiper-charity-next',prevEl:'.swiper-charity-prev',},breakpoints:{0:{slidesPerView:2,spaceBetween:12,},768:{slidesPerView:4.8,spaceBetween:12,},992:{slidesPerView:6,spaceBetween:24,},1200:{slidesPerView:6,spaceBetween:24,},},});var swiper4=new Swiper('.learning-swiper',{slidesPerView:1,spaceBetween:24,navigation:{nextEl:'.learning-swiper-next',prevEl:'.learning-swiper-prev',},breakpoints:{0:{slidesPerView:1.2,spaceBetween:24,},576:{slidesPerView:1.2,spaceBetween:24,},768:{slidesPerView:2.4,spaceBetween:24,},992:{slidesPerView:4,spaceBetween:24,},1200:{slidesPerView:4,spaceBetween:24,},},});var swiper5=new Swiper('.youtube-swiper',{slidesPerView:1,spaceBetween:10,navigation:{nextEl:'.youtube-swiper-next',prevEl:'.youtube-swiper-prev',},breakpoints:{0:{slidesPerView:1.2,spaceBetween:24,},576:{slidesPerView:1.2,spaceBetween:24,},768:{slidesPerView:2.35,spaceBetween:24,},992:{slidesPerView:3,spaceBetween:24,},1200:{slidesPerView:3,spaceBetween:24,},},});var swiper6=new Swiper('.press-swiper',{slidesPerView:1,spaceBetween:24,navigation:{nextEl:'.press-swiper-next',prevEl:'.press-swiper-prev',},breakpoints:{0:{slidesPerView:1.5,spaceBetween:24,},576:{slidesPerView:1.8,spaceBetween:24,},768:{slidesPerView:3.3,spaceBetween:24,},992:{slidesPerView:4,spaceBetween:24,},1200:{slidesPerView:4,spaceBetween:24,},},});$(function(){function modalCloseOnPc()
{if($(this).width()>991&&$('#top-navbar-fullscreen-modal').hasClass('show')){$('#top-navbar-fullscreen-modal').modal('toggle');$('#wallet-connect-fullscreen-modal').modal('toggle');}}
modalCloseOnPc();$(window).on('resize',function(){modalCloseOnPc();});$('.mobile-cwbtn-open').on("click",function(){$('#top-navbar-fullscreen-modal').modal('hide');$('#wallet-connect-fullscreen-modal').modal('show');});$('.mobile-wcbtn-close').on("click",function(){$('#wallet-connect-fullscreen-modal').modal('hide');});});